### ISSUE TITLE
[BUG]No module named 'yaml' 

### ISSUE THREAD

**Issue by jkomak** [awslabs/terraform-iam-policy-validator#7]
**Describe the bug**
**No module named 'yaml'** error while running iam_check.py 

**To Reproduce**

1. Clone the repo
2. Run the following commands
3. pip install --upgrade pip
4.  python3 -m pip install pyyaml
5.  python3 -m pip install pipenv
6.  pipenv install 
7.  pipenv run python iam_check/iam_check.py --config iam_check/config/default.yaml --template-path iam_check/test/tf.json --region us-east-1 --treat-finding-type-as-blocking ERROR

[Container] 2022/09/22 06:14:21 Running command pipenv run python iam_check/iam_check.py --config iam_check/config/default.yaml --template-path iam_check/test/tf.json --region us-east-1 --treat-finding-type-as-blocking ERROR
Traceback (most recent call last):
  File "/codebuild/output/src374232405/src/iam_check/iam_check.py", line 12, in <module>
    import config
  File "/codebuild/output/src374232405/src/iam_check/config.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Expected behavior**
I would expect the command to run without error.

 - OS: Linux.
 - Command running as part of AWS CodeBuild Job.

**Additional context**
[iam-policy-validator.log](https://github.com/awslabs/terraform-iam-policy-validator/files/9625654/iam-policy-validator.log)

**Comment by jkomak** [comment]
I wasn't copying the Pipfile and PipFile.lock to the CodeBuild repo.

It now works as expected. Closing this as its a user error.
